floor(room_1,1).
floor(room_2,1).
floor(room_3,1).
floor(room_4,1).
floor(room_5,1).
floor(lab_1,1).
floor(lab_2,1).
floor(lab_3,1).
floor(lab_4,1).
floor(lab_5,1).
floor(lab_6,1).
floor(wc_man_1_1,1).
floor(wc_woman_1_1,1).
floor(wc_man_1_2,1).
floor(wc_woman_1_2,1).
floor(theater_1,1).
floor(theater_2,1).
floor(students_Affairs,1).
floor(public_relations,1).
floor(security,1).
floor(alsuwitsh,1).
floor(room_9,3).
floor(room_10,3).
floor(training_room,3).
floor(lab_8,3).
floor(lab_9,3).
floor(lab_10,3).
floor(lab_11,3).
floor(lab_12,3).
floor(lab_13,3).
floor(lab_14,3).
floor(lab_physics_1,3).
floor(lab_physics_2,3).
floor(lab_processing,3).
floor(lab_multimedia,3).
floor(iti_room,3).
floor(electronics_lab_1,3).
floor(electronics_lab_2,3).
floor(networks_lab,3).
floor(wc_man_3_1,3).
floor(wc_woman_3_1,3).
floor(wc_man_3_2,3).
floor(wc_woman_3_2,3).
floor(data_center,3).
floor(postgraduate_room,3).
floor(seminar_room,3).
floor(room_7,2).
floor(library,2).
floor(vice_dean_for_environmental_affairs_and_service,2).
floor(vice_dean_for_graduate_studies,2).
floor(vice_dean_for_education_and_student_affairs,2).
floor(college_Council,2).
floor(dean_office,2).
floor(theater_3,2).
floor(theater_4,2).
floor(wc_woman_2,2).
floor(wc_man_2,2).
floor(department_of_Computer_Systems,2).
floor(supporting_Authority_of_computer_Systems_Department,2).%
floor(public_control,2).
floor(department_of_information_Systems,2).
floor(supporting_Authority_of_Information_Systems_Department,2).
floor(secretary_of_the_College,2).
floor(department_of_Scientific_Computing,2).
floor(quality_Assurance_and_Accreditation_Unit,2).
%%%%%%%%%%%%%%%%%%%%%%%%%%
left(room_1,lab_1).
left(room_2,the_East_passage).
left(room_3,wc_man_1_1).
left(room_4,end_passage).
left(room_5,the_storeroom).
left(lab_1,the_main_gate).
left(lab_2,room_2).
left(lab_3,passage).
left(lab_4,lab_3).
left(lab_5,room_4).
left(lab_6,lab_5).
left(wc_man_1_1,wc_woman_1_1).
left(wc_woman_1_1,stairs).
left(wc_man_1_2,wc_woman_1_2).
left(wc_woman_1_2,lab_4).
left(theater_1,passage).
left(theater_2,end_passage).
left(students_Affairs,passage).
left(public_relations,alsuwitsh).
left(security,public_relations).
left(alsuwitsh,theater_1).
left(room_9,triaining_room).
left(room_10,postgraduate_room).
left(training_room,end_passage).
left(lab_8,lab_processing).
left(lab_9,electronics_lab_2).
left(lab_10,wc_man_1_2).
left(lab_11,passage).
left(lab_12,iti_room).
left(lab_13,end_passage).
left(lab_14,stairs).
left(lab_physics_1,stairs).
left(lab_physics_2,lab_physics_1).
left(lab_processing,end_passage).
left(lab_multimedia,wc_man_3_1).
left(electronics_lab_1,lab_8).
left(electronics_lab_2,electronics_lab_1).
left(networks_lab,lab_9).
left(wc_man_3_1,wc_woman_3_1).
left(wc_woman_3_1,stairs).
left(wc_man_3_2,wc_woman_3_2).
left(wc_woman_3_2,stairs).
left(iti_room,lab_12).
left(data_center,passage).
left(postgraduate_room,stairs).
left(seminar_room,lab_10).
left(room_7,vice_dean_for_environmental_affairs_and_service).
left(library,room_7).
left(vice_dean_for_environmental_affairs_and_service,vice_dean_for_graduate_studies).
left(vice_dean_for_graduate_studies,vice_dean_for_education_and_student_affairs).
left(vice_dean_for_education_and_student_affairs,college_Council).
left(college_Council,dean_office).
left(dean_office,store).
left(theater_3,stairs).
left(theater_4,end_passage).
left(wc_man_2,department_of_Computer_System).
left(wc_woman_2,wc_man_2).
left(department_of_Computer_Systems,secretary_of_the_College).
left(supporting_Authority_of_computer_Systems_Department,department_of_Scientific_Computing).%
left(public_control,passage).
left(department_of_information_Systems,the_East_passage).
left(supporting_Authority_of_Information_Systems_Department,department_of_Computer_Systems).
left(secretary_of_the_College,western_emergency_exit).
left(department_of_Scientific_Computing,western_emergency_exit).
left(quality_Assurance_and_Accreditation_Unit,department_of_Scientific_Computing).
%%%%%%%%%%%%%%%%%%%%%
right(room_1,the_East_passage).
right(room_2,lab_2).
right(room_3,passage).
right(room_4,lab_5).
right(room_5,the_Treasury).
right(lab_1,room_1).
right(lab_2,end_passage).
right(lab_3,lab_4).
right(lab_4,passage).
right(lab_5,lab_6).
right(lab_6,store).
right(wc_man_1_1,room_3).
right(wc_woman_1_1,wc_man).
right(wc_man_1_2,end_passage).
right(wc_woman_1_2,wc_man_1_2).
right(theater_1,stairs).
right(theater_2,passage).
right(students_Affairs,asunsir).
right(public_relations,alsuwitsh).
right(security,the_main_gate).
right(alsuwitsh,public_relations).
right(room_9,lab_physics_1).
right(room_10,lab_13).
right(training_room,passage).
right(lab_8,electronics_lab_1).
right(lab_9,network_lab).
right(lab_10,passage).
right(lab_11,stairs).
right(lab_12,lab_multimedia).
right(lab_13,stairs).
right(lab_14,stairs).
right(lab_physics_1,lab_physics_1).
right(lab_physics_2,stairs).
right(lab_processing,lab_8).
right(lab_multimedia,lab_12).
right(electronics_lab_1,electronics_lab_2).
right(electronics_lab_2,lab_9).
right(networks_lab,training_room).
right(wc_man_3_1,passage).
right(wc_woman_3_1,wc_man_3_1).
right(wc_man_3_2,lab_10).
right(wc_woman_3_2,wc_man_3_2).
right(iti_room,lab_11).
right(data_center,passage).
right(postgraduate_room,room_10).
right(seminar_room,data_center).
right(room_7,library).
right(library,store).
right(vice_dean_for_environmental_affairs_and_service,room_7).
right(vice_dean_for_graduate_studies,vice_dean_for_environmental_affairs_and_service).
right(vice_dean_for_education_and_student_affairs,vice_dean_for_graduate_studies).
right(college_Council,vice_dean_for_education_and_student_affairs).
right(dean_office,vice_dean_for_education_and_student_affairs).
right(theater_3,passege).
right(theater_4,passege).
right(wc_woman_2,theater_4).
right(wc_man_2,wc_woman_2).
right(department_of_Computer_Systems,secretary_of_the_College).
right(supporting_Authority_of_computer_Systems_Department,department_of_Computer_Systems).%
right(public_control,stairs).
right(department_of_information_Systems,store).
right(supporting_Authority_of_Information_Systems_Department,department_of_information_Systems).
right(secretary_of_the_College,stairs).
right(department_of_Scientific_Computing,quality_Assurance_and_Accreditation_Unit).
right(quality_Assurance_and_Accreditation_Unit,passage).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ahead(room_1,theater_1).
ahead(room_2,theater_2).
ahead(room_3,students_Affairs).
ahead(room_4,wc_man_1_2).
ahead(room_5,lab_4).
ahead(lab_1,theater_1).
ahead(lab_2,theater_2).
ahead(lab_3,the_store).
ahead(lab_4,the_store).
ahead(lab_5,passage).
ahead(lab_6,passge).
ahead(wc_man_1_1,students_Affairs).
ahead(wc_woman_1_1,students_Affairs).
ahead(wc_man_1_2,room_4).
ahead(wc_woman_1_2,room_4).
ahead(theater_1,public_relations).
ahead(theater_2,lab_2).
ahead(students_Affairs,room_3).
ahead(public_relations,theater_1).
ahead(security,lab_1).
ahead(alsuwitsh,theater_1).
ahead(room_9,lab_10).
ahead(room_10,lab_multimadia).
ahead(training_room,passage).
ahead(lab_8,passage).
ahead(lab_9,data_center).
ahead(lab_10,room_9).
ahead(lab_11,postgraduate_room).
ahead(lab_12,room_10).
ahead(lab_13,wc_man_3_1).
ahead(lab_14,wc_wonman_3_1).
ahead(lab_physics_1,lab_11).
ahead(lab_physics_2,passage).
ahead(lab_processing,passage).
ahead(lab_multimedia,room_10).
ahead(electronics_lab_1,data_center).
ahead(electronics_lab_2,data_center).
ahead(networks_lab,seminar_room).
ahead(wc_man_3_1,lab_14).
ahead(wc_woman_3_1,lab_14).
ahead(wc_man_3_2,room_9).
ahead(wc_woman_3_2,room_9).
ahead(iti_room,postgraduate_room).
ahead(postgraduate_room,lab_11).
ahead(data_center,lab_9).
ahead(seminar_room,network_lab).
ahead(room_7,theater_4).
ahead(library,theater_4).
ahead(vice_dean_for_environmental_affairs_and_service,theater_3).
ahead(vice_dean_for_graduate_studies,theater_3).
ahead(vice_dean_for_education_and_student_affairs,theater_3).
ahead(college_Council,passage).
ahead(dean_office,quality_Assurance_and_Accreditation_Unit).
ahead(secretary_of_the_dean,quality_Assurance_and_Accreditation_Unit).
ahead(theater_3,quality_Assurance_and_Accreditation_Unit).
ahead(theater_4,supporting_Authority_of_Information_Systems_Department).
ahead(wc_woman_2,supporting_Authority_of_Information_Systems_Department).
ahead(wc_man_2,supporting_Authority_of_Information_Systems_Department).
ahead(department_of_Computer_Systems,passage).
ahead(supporting_Authority_of_computer_Systems_Department,passage).%
ahead(public_control,department_of_Scientific_Computing).
ahead(department_of_information_Systems,passage).
ahead(supporting_Authority_of_Information_Systems_Department,wc_woman_2).
ahead(secretary_of_the_College,passage).
ahead(department_of_Scientific_Computing,public_control).
ahead(quality_Assurance_and_Accreditation_Unit,theater_3).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
path(X,P):-floor(X,Z),left(X,L),right(X,R),ahead(X,A),P=[floor_Number,Z,in_front_of,A,in_left,L,and_in_right,R].
paths(Number,Z):-floor(Z,Number).