/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nafea
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import org.jpl7.*;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        String swimap = "consult('map.pl')";
        Query qmap = new Query(swimap);

        System.out.println(qmap.hasSolution() ? "ss" : "ff");

        String swiperson = "consult('person.pl')";

        Query qperson = new Query(swiperson);
        System.out.println(qperson.hasSolution() ? "sp" : "fp");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        place = new javax.swing.JRadioButton();
        preson = new javax.swing.JRadioButton();
        answertxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        questiontxt = new javax.swing.JTextField();
        resetbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 51, 255));
        setForeground(getBackground());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/111.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/222.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Answer.");

        place.setBackground(new java.awt.Color(255, 255, 255));
        place.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        place.setForeground(new java.awt.Color(102, 102, 102));
        place.setText("Place");
        place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeActionPerformed(evt);
            }
        });

        preson.setBackground(new java.awt.Color(255, 255, 255));
        preson.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        preson.setForeground(new java.awt.Color(102, 102, 102));
        preson.setText("Person");
        preson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presonActionPerformed(evt);
            }
        });

        answertxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        answertxt.setForeground(new java.awt.Color(51, 51, 51));
        answertxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        answertxt.setAlignmentX(0.9F);
        answertxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        answertxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        answertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answertxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("What's Your Category ?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("What's Your Question ?");

        questiontxt.setBackground(new java.awt.Color(17, 59, 184));
        questiontxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        questiontxt.setForeground(new java.awt.Color(255, 255, 255));
        questiontxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        questiontxt.setAlignmentX(0.9F);
        questiontxt.setBorder(null);
        questiontxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        questiontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questiontxtActionPerformed(evt);
            }
        });

        resetbtn.setBackground(new java.awt.Color(255, 255, 255));
        resetbtn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(102, 102, 102));
        resetbtn.setText("Reset");
        resetbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        resetbtn.setBorderPainted(false);
        resetbtn.setHideActionText(true);
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(255, 255, 255));
        searchbtn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(102, 102, 102));
        searchbtn.setText("Search");
        searchbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        searchbtn.setBorderPainted(false);
        searchbtn.setHideActionText(true);
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(place)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(preson)))))
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questiontxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(place)
                    .addComponent(preson))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(answertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void presonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presonActionPerformed
        // TODO add your handling code here:
 
        place.setSelected(false);
        answertxt.setText("");
    }//GEN-LAST:event_presonActionPerformed

    private void placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeActionPerformed
        // TODO add your handling code here:
 
        preson.setSelected(false);

        answertxt.setText("");
    }//GEN-LAST:event_placeActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed

        place.setSelected(false);
        preson.setSelected(false);
        questiontxt.setText("");
        answertxt.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_resetbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed

        if (place.isSelected()) {
            try {
                String s1 = questiontxt.getText().toLowerCase();
                if (s1.contains("path")) {

                    char[] c = s1.toCharArray();

                    int size = s1.length();
                    System.out.println(size);
                    c[size - 1] = ',';

                    //System.out.println(c);
                    String s2 = new String(c);
                    //	System.out.println(s2);
                    String s3 = s2 + "A).";
                    System.out.println(s3);
                    Query Q2 = new Query(s3);
                    if (Q2.hasSolution()) {

                        String s = Q2.oneSolution().get("A").toString();

                        s = s.replace("\'", "");
                        s = s.replace("|", "");
                        s = s.replace("[", "");
                        s = s.replace(")", "");
                        s = s.replace("(", "");
                        s = s.replace("]", "");
                        s = s.replace("_", " ");
                        s = s.replace(",", " ");

                        //	System.out.println(s);
                        answertxt.setText(s);

                    } else {
                        answertxt.setText("That not place please enter again ");
                    }

                } else {
                    answertxt.setText("You don't enter name or entering  syntax error try again ");
                }

            } catch (Exception e) {
                answertxt.setText("You don't enter elment or don't enter the correct syntax");
            }

        } else if (preson.isSelected()) {

            try {

                String s1 = questiontxt.getText().toLowerCase();

                if (s1.contains("person")) {
                    char[] c = s1.toCharArray();

                    int size = s1.length();
                    System.out.println(size);
                    c[size - 1] = ',';

                    //System.out.println(c);
                    String s2 = new String(c);
                    //	System.out.println(s2);
                    String s3 = s2 + "A).";
                    System.out.println(s3);
                    Query Q2 = new Query(s3);
                    if (Q2.hasSolution()) {

                        String s = Q2.oneSolution().get("A").toString();

                        s = s.replace("\'", "");
                        s = s.replace("|", "");
                        s = s.replace("[", "");
                        s = s.replace(")", "");
                        s = s.replace("(", "");
                        s = s.replace("]", "");
                        s = s.replace("_", " ");
                        s = s.replace(",", " ");

                        //	System.out.println(s);
                        s=s.replace("dr","DR");
                        s=s.replace("ta","TA");
                        answertxt.setText(s);

                    } else {
                        answertxt.setText("The person that you enter isn't in collage ");
                    }

                } else {
                    answertxt.setText("You don't enter name or entering  syntax error try again ");
                }
            } catch (Exception e) {
                answertxt.setText("You don't enter name or entering  syntax error try again");
            }

        } else {
            answertxt.setText("");
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void answertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answertxtActionPerformed

    private void questiontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questiontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questiontxtActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        help next=new help();
         next.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answertxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton place;
    private javax.swing.JRadioButton preson;
    private javax.swing.JTextField questiontxt;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables

}
